---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-vnet-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-vnet.lhns.de
  resources:
  - clustervirtualnetworkbaselines
  - virtualnetworkbaselines
  - virtualnetworkbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kube-vnet.lhns.de
  resources:
  - clustervirtualnetworkbaselines/status
  - virtualnetworkbaselines/status
  - virtualnetworkbindings/status
  - virtualnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kube-vnet.lhns.de
  resources:
  - virtualnetworkbindings/finalizers
  - virtualnetworks/finalizers
  verbs:
  - update
- apiGroups:
  - kube-vnet.lhns.de
  resources:
  - virtualnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
